name: 'Bundle Release Assets'
description: 'Downloads build assets and packages them into a zip file along with game data and libraries'
runs:
  using: "composite"
  steps:
    - run: mkdir release
      shell: bash

    - name: Download build artefacts
      uses: actions/download-artifact@v3
      with:
        path: release

    - run: ls -R release
      shell: bash

    - name: Compress Windows Release
      shell: bash
      run: |
        zip -j CortexCommand.windows.zip \
          "release/Cortex Command.exe" \
          external/lib/win/{fmod,SDL2}.dll

    - name: Compress Linux Release
      shell: bash
      run: |
        zip -j CortexCommand.linux.zip \
          "release/CortexCommand (Linux)/CortexCommand.AppImage" \
          external/lib/linux/x86_64/libfmod.so*

    - name: Compress OSX Release
      shell: bash
      run: |
        zip -j CortexCommand.macos.zip \
          "release/CortexCommand (macOS)/CortexCommand" \
          external/lib/macos/libfmod.dylib

    - name: Package Data files
      shell: bash
      run: |
        zip -r -u CortexCommand.windows.zip Data
        zip -r -u CortexCommand.linux.zip Data
        zip -r -u CortexCommand.macos.zip Data


 
 
  