name: 'Set Version'
description: 'Updates all references to the current game version'
inputs:
  new_release_version: 
    description: 'The new version string'
    required: true
  commit_changes:
    description: 'Whether to commit the changes or not'
    required: false
    default: "false"
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Constants.h GameVersion
      run: sed -i -E '/c_GameVersion = /s/"[^"]*"/"${{inputs.new_release_version}}"/' System/Constants.h
      shell: bash

    - uses: actions/setup-python@v3

    - name: Rewrite meson version
      run: |
        pip install meson
        meson rewrite kwargs set project // version ${{ inputs.new_release_version }}
      shell: bash

    - name: Commit and push Version Changes
      if: ${{ inputs.commit_changes == 'true' }}
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add System/GameVersion.h meson.build
        git commit -m "Update version" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

